name: vcpkg

on: [push, pull_request]

jobs:
  job:
    name: ${{ matrix.platform }}-${{ github.workflow }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-11, windows-2019, windows-2022]
        platform: [macos-11]
        include:
          - platform: macos-11
            vcpkg: '/usr/local/share/vcpkg'
            triplet: 'x64-osx-11'
          # - platform: windows-2019
          #   vcpkg: 'C:\vcpkg'
          #   triplet: 'x64-windows'
          # - platform: windows-2022
          #   vcpkg: 'C:\vcpkg'
          #   triplet: 'x64-windows'
    env:
      VCPKG_COMMIT_ID: 'acc3bcf76b84ae5041c86ab55fe138ae7b8255c7'
      VCPKG_ROOT: '${{ matrix.vcpkg }}'
      VCPKG_INSTALLED_DIR: '${{ github.workspace }}/deps/vcpkg_installed/${{ matrix.platform }}'
      VCPKG_DEFAULT_TRIPLET: '${{ matrix.triplet }}'
      VCPKG_OVERLAY_TRIPLETS: '${{ github.workspace }}/triplets'
    steps:
      - name: Get more disk space
        run:  |
          rm -rvf '${GOROOT_1_17_X64}'
          rm -rvf '${GOROOT_1_18_X64}'
          rm -rvf '${GOROOT_1_19_X64}'
          rm -rvf '${JAVA_HOME_11_X64}'
          rm -rvf '${JAVA_HOME_13_X64}'
          rm -rvf '${JAVA_HOME_17_X64}'
          rm -rvf '${JAVA_HOME_8_X64}'
          rm -rvf '${{ matrix.vcpkg }}'
          rm -rvf '/Users/runner/Library/Android'
          rm -rvf 'C:\Android'
          rm -rvf 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools'
          rm -rvf 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools'
          rm -rvf 'C:\Program Files\dotnet'
          rm -rvf 'C:\Program Files\dotnet'
          rm -rvf 'C:\SeleniumWebDrivers'
          rm -rvf 'C:\selenium'
          rm -rvf 'C:\tools\Apache24'
          rm -rvf 'C:\tools\nginx-1.23.1'
        shell: bash
        continue-on-error: true
      - name: Install missing dependencies
        run:   |
               if [ "$RUNNER_OS" == "macOS" ]; then
                    brew install autoconf-archive automake libtool md4c
               fi
        shell: bash
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Update cmake
        uses: lukka/get-cmake@latest
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ env.VCPKG_ROOT }}'
          vcpkgGitCommitId: '${{ env.VCPKG_COMMIT_ID }}'
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: true
      - name: Compress packages
        run: |
          tar -czpf '${{ github.workspace }}/${{ matrix.platform }}.tar.gz' -C '${{ github.workspace }}/deps/vcpkg_installed' '${{ matrix.platform }}'
      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: 'packages-${{ matrix.platform }}'
          path: '${{ github.workspace }}/${{ matrix.platform }}.tar.gz'
